damin/damin/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('project.urls')),
]

damin/project/urls.py
from django.urls import path
from . import views

app_name = 'project'
urlpatterns = [
	# ex: /project/
    path('', views.dashboard, name='dashboard'),
    path('proses', views.proses, name='proses'),
    path('desc', views.desc, name='desc'),
    path('table', views.table, name='table'),
    path('visualisasi', views.visualisasi, name='visualisasi'),
    path('data', views.data, name='data'),
]

damin/project/models.py
from django.db import models

# Create your models here.

damin/project/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.http import Http404

def dashboard(request):
	return render(request, "project/dashboard.html", {})

def proses(request):
	return render(request, "project/proses.html", {})

def desc(request):
	return render(request, "project/desc.html", {})

def table(request):
	return render(request, "project/table.html", {})

def visualisasi(request):
	return render(request, "project/visualisasi.html", {})

def data(request):
	return render(request, "project/data.html", {})

damin/project/templates/project/dashboard.html
<!doctype html>
<html>
<head>
	<style type="text/css">
		.sidenav {
			height:100%;
			width:160px;
			position: fixed;
			z-index:1;
			top:0;
			left:0;
			background-color: #C4C4C4;
			overflow-x:hidden;
			padding-top:50px;
		}
 
		.sidenav a {
			padding:6px 8px 6px 16px;
			text-decoration: none;
			font-size:20px;
			color:black;
			display:block;
            font-weight: 500;
		}
 
		.sidenav a:hover{
			color:#f1f1f1;
		}	
 
		.main{
			margin-left:180px;
			padding: 10px 20px;
		}
        

	</style>
    <title>{% block title %}Project Damin{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
 
<body>
	<div class="sidenav">
		<a href="{% url "project:proses" %}">Proses</a>
		<a href="{% url "project:desc" %}">Deskripsi Data</a>
		<a href="{% url "project:table" %}">Table</a>
		<a href="{% url "project:visualisasi" %}">Visualisasi</a>
		<a href="{% url "project:data" %}">Desc Data</a>
    </div>
 
    {% block content %}
    <div class="main">
        <h2>Dashboard</h2>
        <hr>
        <h3>ini content</h3>
    </div>
	{% endblock %}
 
</body>
</html>

damin/project/templates/project/data.html
<!doctype html>
<html>
<head>
	<style type="text/css">
		.sidenav {
			height:100%;
			width:160px;
			position: fixed;
			z-index:1;
			top:0;
			left:0;
			background-color: #C4C4C4;
			overflow-x:hidden;
			padding-top:50px;
		}
 
		.sidenav a {
			padding:6px 8px 6px 16px;
			text-decoration: none;
			font-size:20px;
			color:black;
			display:block;
            font-weight: 500;
		}
 
		.sidenav a:hover{
			color:#f1f1f1;
		}	
 
		.main{
			margin-left:180px;
			padding: 10px 20px;
		}
        

	</style>
    <title>{% block title %}Project Damin{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
 
<body>
	<div class="sidenav">
		<a href="{% url "project:proses" %}">Proses</a>
		<a href="{% url "project:desc" %}">Deskripsi Data</a>
		<a href="{% url "project:table" %}">Table</a>
		<a href="{% url "project:visualisasi" %}">Visualisasi</a>
		<a href="{% url "project:data" %}">Desc Data</a>
    </div>
 
    {% block content %}
    <div class="main">
       <div >
		  <h2>Visualisasi</h2>
		  <hr>
		  <div class="container-sm" >
			<div class="row">
				<div class="col-md-3" >
					<form>
				
						<div class="form-group">
						  <label for="exampleFormControlSelect1">Example select</label>
						  <select class="form-control" id="exampleFormControlSelect1">
							<option> Line </option>
							<option> Area </option>
							<option> Histogram </option>
							<option> Scatter Plot </option>
							<option> Boxplot </option>
						  </select>
						</div>
		
		
						<div class="form-group">
							<label for="exampleFormControlSelect1">Example select</label>
							<select class="form-control" id="exampleFormControlSelect1">
								<option> Atribut 1 </option>
								<option> Atribut 2 </option>
								<option> Atribut 3 </option>
								<option> Atribut 4  </option>
								<option> Atribut 5 </option>
							</select>
						  </div>
		
		
						  <div class="form-group">
							<label for="exampleFormControlSelect1">Example select</label>
							<select class="form-control" id="exampleFormControlSelect1">
								<option> Atribut 1 </option>
								<option> Atribut 2 </option>
								<option> Atribut 3 </option>
								<option> Atribut 4  </option>
								<option> Atribut 5 </option>
							</select>
						  </div>
		
		
						  <div class="form-group">
							<label for="exampleFormControlSelect1">Example select</label>
							<select class="form-control" id="exampleFormControlSelect1">
								<option> Merah </option>
								<option>Kuning </option>
								<option> Hijau </option>
								<option> Biru </option>
								<option> Ungu </option>
							</select>
						  </div>
						
						
					  </form>

					
				</div>

				<div class="col-md-8">
					<div class="d-flex justify-content-center" style="margin-top: 100px;">
						<div style="height: 200px; width: 50%; background-color:grey;">
							
					
						</div>

					</div>
					

					
				</div>

			</div>


			
		
		
	  </div>

	  
	  


	 

    </div>
    </div>
	{% endblock %}
 
</body>
</html>

damin/project/templates/project/desc.html
<!doctype html>
<html>
<head>
	<style type="text/css">
		.sidenav {
			height:100%;
			width:160px;
			position: fixed;
			z-index:1;
			top:0;
			left:0;
			background-color: #C4C4C4;
			overflow-x:hidden;
			padding-top:50px;
		}
 
		.sidenav a {
			padding:6px 8px 6px 16px;
			text-decoration: none;
			font-size:20px;
			color:black;
			display:block;
            font-weight: 500;
		}
 
		.sidenav a:hover{
			color:#f1f1f1;
		}	
 
		.main{
			margin-left:180px;
			padding: 10px 20px;
		}
        
		.item-header{

		}

	</style>
    <title>{% block title %}Project Damin{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
 
<body>
	<div class="sidenav">
		<a href="{% url "project:proses" %}">Proses</a>
		<a href="{% url "project:desc" %}">Deskripsi Data</a>
		<a href="{% url "project:table" %}">Table</a>
		<a href="{% url "project:visualisasi" %}">Visualisasi</a>
		<a href="{% url "project:data" %}">Desc Data</a>
    </div>
 
    {% block content %}
    <div class="main">
        <h2>Data Description</h2>
        <hr>
		<div class="card bg-light mb-3" style="max-width: 25rem;">
			<div class="card-header">
				General
			</div>
			<div class="container m-2">
				<div class="row">
					<div class="col-4">
						Keterangan 1
					</div>
					<div class="col-8">
						Variable width content
					</div>
				</div>
			</div>
		</div>
		<div class="card bg-light mb-3" style="max-width: 25rem;">
			<div class="card-header">
				Removing Outliers
			</div>
			<div class="container m-2">
				<div class="row">
					<div class="col-4">
						Keterangan 1
					</div>
					<div class="col-8">
						Variable width content
					</div>
				</div>
			</div>
		</div>
	</div>
	{% endblock %}
 
</body>
</html>

damin/project/templates/project/proses.html
<!doctype html>
<html>
<head>
	<style type="text/css">
		.sidenav {
			height:100%;
			width:160px;
			position: fixed;
			z-index:1;
			top:0;
			left:0;
			background-color: #C4C4C4;
			overflow-x:hidden;
			padding-top:50px;
		}
 
		.sidenav a {
			padding:6px 8px 6px 16px;
			text-decoration: none;
			font-size:20px;
			color:black;
			display:block;
            font-weight: 500;
		}
 
		.sidenav a:hover{
			color:#f1f1f1;
		}	
 
		.main{
			margin-left:180px;
			padding: 10px 20px;
		}
        

	</style>
    <title>{% block title %}Project Damin{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
 
<body>
	<div class="sidenav">
		<a href="{% url "project:proses" %}">Proses</a>
		<a href="{% url "project:desc" %}">Deskripsi Data</a>
		<a href="{% url "project:table" %}">Table</a>
		<a href="{% url "project:visualisasi" %}">Visualisasi</a>
		<a href="{% url "project:data" %}">Desc Data</a>
    </div>
 
    {% block content %}
    <div class="main">
        <h2>Proses</h2>
        <hr>
        <h3>ini content</h3>
    </div>
	{% endblock %}
 
</body>
</html>

damin/project/templates/project/table.html
<!doctype html>
<html>
<head>
	<style type="text/css">
		.sidenav {
			height:100%;
			width:160px;
			position: fixed;
			z-index:1;
			top:0;
			left:0;
			background-color: #C4C4C4;
			overflow-x:hidden;
			padding-top:50px;
		}
 
		.sidenav a {
			padding:6px 8px 6px 16px;
			text-decoration: none;
			font-size:20px;
			color:black;
			display:block;
            font-weight: 500;
		}
 
		.sidenav a:hover{
			color:#f1f1f1;
		}	
 
		.main{
			margin-left:180px;
			padding: 10px 20px;
		}

		.content{
			border: black 2px solid;
			padding: 10px 10px 10px 10px;
		}

		table, th, td {
			border: 1px solid black;
		}
        

	</style>
    <title>{% block title %}Project Damin{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
 
<body>
	<div class="sidenav">
		<a href="{% url "project:proses" %}">Proses</a>
		<a href="{% url "project:desc" %}">Deskripsi Data</a>
		<a href="{% url "project:table" %}">Table</a>
		<a href="{% url "project:visualisasi" %}">Visualisasi</a>
		<a href="{% url "project:data" %}">Desc Data</a>
    </div>
 
    {% block content %}
    <div class="main">
        <h2>Table</h2>
		<hr>
		<div class="content">
			<table style="width:100%">
				<tr>
					<th>Firstname</th>
					<th>Lastname</th>
					<th>Age</th>
				</tr>
				<tr>
					<td>Jill</td>
					<td>Smith</td>
					<td>50</td>
				</tr>
				<tr>
					<td>Eve</td>
					<td>Jackson</td>
					<td>94</td>
				</tr>
			</table>
		</div>
    </div>
	{% endblock %}
 
</body>
</html>

damin/project/templates/project/visualisasi.html
<!doctype html>
<html>
<head>
	<style type="text/css">
		.sidenav {
			height:100%;
			width:160px;
			position: fixed;
			z-index:1;
			top:0;
			left:0;
			background-color: #C4C4C4;
			overflow-x:hidden;
			padding-top:50px;
		}
 
		.sidenav a {
			padding:6px 8px 6px 16px;
			text-decoration: none;
			font-size:20px;
			color:black;
			display:block;
            font-weight: 500;
		}
 
		.sidenav a:hover{
			color:#f1f1f1;
		}	
 
		.main{
			margin-left:180px;
			padding: 10px 20px;
		}
        

	</style>
    <title>{% block title %}Project Damin{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
 
<body>
	<div class="sidenav">
		<a href="{% url "project:proses" %}">Proses</a>
		<a href="{% url "project:desc" %}">Deskripsi Data</a>
		<a href="{% url "project:table" %}">Table</a>
		<a href="{% url "project:visualisasi" %}">Visualisasi</a>
		<a href="{% url "project:data" %}">Desc Data</a>
    </div>
 
    {% block content %}
    <div class="main">
       <div >
		  <h2>Visualisasi</h2>
		  <hr>
		  <div class="container-sm" >
			<div class="row">
				<div class="col-md-3" >
					<form>
				
						<div class="form-group">
						  <label for="exampleFormControlSelect1">Example select</label>
						  <select class="form-control" id="exampleFormControlSelect1">
							<option> Line </option>
							<option> Area </option>
							<option> Histogram </option>
							<option> Scatter Plot </option>
							<option> Boxplot </option>
						  </select>
						</div>
		
		
						<div class="form-group">
							<label for="exampleFormControlSelect1">Example select</label>
							<select class="form-control" id="exampleFormControlSelect1">
								<option> Atribut 1 </option>
								<option> Atribut 2 </option>
								<option> Atribut 3 </option>
								<option> Atribut 4  </option>
								<option> Atribut 5 </option>
							</select>
						  </div>
		
		
						  <div class="form-group">
							<label for="exampleFormControlSelect1">Example select</label>
							<select class="form-control" id="exampleFormControlSelect1">
								<option> Atribut 1 </option>
								<option> Atribut 2 </option>
								<option> Atribut 3 </option>
								<option> Atribut 4  </option>
								<option> Atribut 5 </option>
							</select>
						  </div>
		
		
						  <div class="form-group">
							<label for="exampleFormControlSelect1">Example select</label>
							<select class="form-control" id="exampleFormControlSelect1">
								<option> Merah </option>
								<option>Kuning </option>
								<option> Hijau </option>
								<option> Biru </option>
								<option> Ungu </option>
							</select>
						  </div>
						
						
					  </form>

					
				</div>

				<div class="col-md-8">
					<div class="d-flex justify-content-center" style="margin-top: 100px;">
						<div style="height: 200px; width: 50%; background-color:grey;">
							
					
						</div>

					</div>
					

					
				</div>

			</div>


			
		
		
	  </div>

	  
	  


	 

    </div>
    </div>
	{% endblock %}
 
</body>
</html>